name: Run linter & tests

on: [push, pull_request]

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13.x'
      - name: Install golangci-lint
        run: go get -v golang.org/x/lint/golint
      - name: Run linter
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          golint ./...

  test:
    name: Tests
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Run tests
        run: go test -v ./...